package pedroPathing.AutoClass.EnumeratedState;

public enum State {
    STATE_START,
    STATE_MOVE_TO_SUBMERSIBLE,
    STATE_MOVE_TO_AND_SCORE,
    STATE_MOVE_BACK_FROM_SUBMERSIBLE,
    STATE_CLR_SUBMERSIBLE,
    STATE_MOVE_TO_PUSH_COLOR_SAMPLE,
    STATE_PUSH_COLOR_SAMPLE_ONE,
    STATE_MOVE_TO_SAMPLE_TWO,
    STATE_PUSH_COLOR_SAMPLE_TWO,
    STATE_MOVE_TO_SAMPLE_THREE,
    STATE_PUSH_COLOR_SAMPLE_THREE,
    STATE_MOVE_PICKUP_SAMPLE,
    STATE_MOVE_PUT_SAMPLE_ONE,
    STATE_MOVE_PUT_SAMPLE_TWO,
    STATE_MOVE_PUT_SAMPLE_THREE,
    STATE_HOME

}
